
READ = "read"
WRITE = "write"
DELETE = "delete"

GENERAL_USER_SETTINGS = "general.user_settings"
GENERAL_SYSTEM_SETTINGS = "general.system_settings"
GENERAL_GROUP_SETTINGS = "general.group_settings"
GENERAL_MY_ACCOUNT = "general.my_account"

MONITORING_POLICY_SETTINGS = "monitoring.policy_settings"

VISUALIZATION_DASHBOARD = "visualization.dashboard"
VISUALIZATION_TEMPLATE = "visualization.template"
VISUALIZATION_WIDGET = "visualization.widget"
VISUALIZATION_INVENTORY = "visualization.inventory"
VISUALIZATION_METRIC_EXPLORER = "visualization.metric_explorer"
VISUALIZATION_LOG_EXPLORER = "visualization.log_explorer"
VISUALIZATION_FLOW_EXPLORER = "visualization.flow_explorer"
VISUALIZATION_NETROUTE = "visualization.netroute"
VISUALIZATION_TRAP_EXPLORER = "visualization.trap_explorer"
VISUALIZATION_TOPOLOGY = "visualization.topology"


ROLE_CREATE = "role:create"
ROLE_VIEW = "role:view"
ROLE_UPDATE = "role:update"
ROLE_DELETE = "role:delete"

USER_CREATE = "user:create"
USER_VIEW = "user:view"
USER_UPDATE = "user:update"
USER_DELETE = "user:delete"


UI_PERMISSION_MAP = {
    "User Settings": GENERAL_USER_SETTINGS,
    "System Settings": GENERAL_SYSTEM_SETTINGS,
    "Group Settings": GENERAL_GROUP_SETTINGS,
    "My Account": GENERAL_MY_ACCOUNT,

    "Policy Settings": MONITORING_POLICY_SETTINGS,

    "Dashboard": VISUALIZATION_DASHBOARD,
    "Template": VISUALIZATION_TEMPLATE,
    "Widget": VISUALIZATION_WIDGET,
    "Inventory": VISUALIZATION_INVENTORY,
    "Metric Explorer": VISUALIZATION_METRIC_EXPLORER,
    "Log Explorer": VISUALIZATION_LOG_EXPLORER,
    "Flow Explorer": VISUALIZATION_FLOW_EXPLORER,
    "NetRoute": VISUALIZATION_NETROUTE,
    "Trap Explorer": VISUALIZATION_TRAP_EXPLORER,
    "Topology": VISUALIZATION_TOPOLOGY,
}


ALL_PERMISSIONS = [
    GENERAL_USER_SETTINGS,
    GENERAL_SYSTEM_SETTINGS,
    GENERAL_GROUP_SETTINGS,
    GENERAL_MY_ACCOUNT,
    MONITORING_POLICY_SETTINGS,
    VISUALIZATION_DASHBOARD,
    VISUALIZATION_TEMPLATE,
    VISUALIZATION_WIDGET,
    VISUALIZATION_INVENTORY,
    VISUALIZATION_METRIC_EXPLORER,
    VISUALIZATION_LOG_EXPLORER,
    VISUALIZATION_FLOW_EXPLORER,
    VISUALIZATION_NETROUTE,
    VISUALIZATION_TRAP_EXPLORER,
    VISUALIZATION_TOPOLOGY,
]
